# Generated by Django 3.0.4 on 2020-03-28 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeportal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem_statements',
            name='test_case',
            field=models.FileField(default=None, upload_to='testcases'),
            preserve_default=False,
        ),
    ]
