# Generated by Django 3.0.4 on 2020-03-28 10:03

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeportal', '0003_problem_statements_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem_statements',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2020, 3, 28, 15, 33, 49, 403578)),
        ),
        migrations.AlterField(
            model_name='problem_statements',
            name='example',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='problem_statements',
            name='input_format',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='problem_statements',
            name='output_format',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='problem_statements',
            name='problem',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
