# Generated by Django 3.0.4 on 2020-03-28 16:47

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeportal', '0004_auto_20200328_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem_statements',
            name='problem_name',
            field=ckeditor.fields.RichTextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='problem_statements',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2020, 3, 28, 22, 17, 25, 352414)),
        ),
    ]
