# Generated by Django 3.0.4 on 2020-03-28 19:16

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeportal', '0005_auto_20200328_2217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contestant', models.TextField()),
                ('probstatement', models.TextField()),
                ('submissions', models.TextField()),
                ('check', models.BooleanField()),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='problem_statements',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2020, 3, 29, 0, 46, 0, 118152)),
        ),
        migrations.AlterField(
            model_name='problem_statements',
            name='test_case',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
