# Generated by Django 3.0.4 on 2020-03-28 19:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeportal', '0006_auto_20200329_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem_statements',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2020, 3, 29, 0, 58, 57, 628856)),
        ),
        migrations.AlterField(
            model_name='problem_statements',
            name='test_case',
            field=models.TextField(),
        ),
    ]
