# Generated by Django 3.0.4 on 2020-03-28 19:45

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeportal', '0007_auto_20200329_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem_statements',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2020, 3, 29, 1, 15, 35, 438804)),
        ),
        migrations.AlterField(
            model_name='problem_statements',
            name='test_case',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
