# Generated by Django 3.0.4 on 2020-03-29 19:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeportal', '0011_auto_20200329_0141'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem_statements',
            name='show',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='problem_statements',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 30, 0, 58, 18, 888626)),
        ),
    ]
