# Generated by Django 3.0.4 on 2020-03-29 20:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeportal', '0012_auto_20200330_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem_statements',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 30, 2, 0, 35, 805399)),
        ),
    ]
