# Generated by Django 3.0.4 on 2020-03-30 17:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeportal', '0014_auto_20200330_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem_statements',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 30, 22, 47, 39, 12043)),
        ),
    ]
