# Generated by Django 3.0.4 on 2020-03-31 17:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeportal', '0015_auto_20200330_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='output',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='problem_statements',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 31, 23, 15, 43, 644920)),
        ),
    ]
