# Generated by Django 3.0.4 on 2020-03-31 21:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeportal', '0018_auto_20200401_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem_statements',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 1, 2, 58, 22, 780497)),
        ),
    ]
