# Generated by Django 3.0.4 on 2020-04-01 08:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeportal', '0019_auto_20200401_0258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem_statements',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 1, 13, 47, 3, 52462)),
        ),
    ]
