# Generated by Django 3.0.4 on 2020-04-01 08:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeportal', '0020_auto_20200401_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem_statements',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 1, 14, 7, 24, 398158)),
        ),
    ]
