# Generated by Django 3.0.4 on 2020-04-15 06:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeportal', '0038_auto_20200415_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem_statements',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 15, 12, 4, 33, 280102)),
        ),
    ]
