# Generated by Django 3.0.4 on 2020-04-15 07:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeportal', '0039_auto_20200415_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem_statements',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 15, 13, 27, 30, 602819)),
        ),
    ]
