# Generated by Django 3.0.4 on 2020-04-15 17:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeportal', '0045_auto_20200415_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem_statements',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 15, 23, 27, 3, 567122)),
        ),
    ]
