# Generated by Django 3.0.4 on 2020-04-15 17:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('codeportal', '0046_auto_20200415_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem_statements',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
