# Generated by Django 3.0.4 on 2020-04-15 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aces', '0007_auto_20200415_1155'),
        ('accounts', '0003_remove_userphotos_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userphotos',
            name='event',
            field=models.ManyToManyField(to='aces.Event'),
        ),
        migrations.AddField(
            model_name='userphotos',
            name='team',
            field=models.ManyToManyField(to='aces.Team'),
        ),
    ]
