# Generated by Django 3.0.4 on 2020-04-15 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200415_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userphotos',
            name='event',
        ),
        migrations.RemoveField(
            model_name='userphotos',
            name='team',
        ),
    ]
