# Generated by Django 3.0.4 on 2020-03-31 20:50

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', ckeditor.fields.RichTextField()),
                ('date', models.DateField(default=datetime.datetime(2020, 4, 1, 2, 20, 28, 956661))),
                ('picture', models.ImageField(upload_to='pics/')),
                ('body', ckeditor.fields.RichTextField()),
                ('footer', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
