# Generated by Django 3.0.4 on 2020-04-01 08:17

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200401_0258'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogposts',
            name='blogurl',
            field=models.TextField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogposts',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 4, 1, 13, 47, 2, 989151)),
        ),
        migrations.AlterField(
            model_name='blogposts',
            name='title',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
