# Generated by Django 3.0.4 on 2020-04-01 08:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200401_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogposts',
            name='nextblogurl',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogposts',
            name='prevblogurl',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogposts',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 4, 1, 14, 7, 24, 351326)),
        ),
    ]
