# Generated by Django 3.0.4 on 2020-04-15 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20200415_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogposts',
            name='blogurl',
        ),
        migrations.RemoveField(
            model_name='blogposts',
            name='nextblogurl',
        ),
        migrations.RemoveField(
            model_name='blogposts',
            name='prevblogurl',
        ),
    ]
