# Generated by Django 3.0.4 on 2020-04-15 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20200415_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogposts',
            name='title',
            field=models.TextField(),
        ),
    ]
