# Generated by Django 3.0.4 on 2020-04-15 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20200415_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogposts',
            name='nextblogtitle',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogposts',
            name='prevblogtitle',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
