# Generated by Django 3.0.4 on 2020-04-14 11:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aces', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_contact',
        ),
        migrations.AddField(
            model_name='event',
            name='event_contact',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
