# Generated by Django 3.0.4 on 2020-04-14 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aces', '0002_auto_20200414_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='team_members',
        ),
    ]
