# Generated by Django 3.0.4 on 2020-04-14 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aces', '0004_team_team_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='slugname',
            field=models.TextField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
