# Generated by Django 3.0.4 on 2020-04-14 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aces', '0005_team_slugname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='slugname',
        ),
    ]
