# Generated by Django 3.0.4 on 2020-04-15 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aces', '0006_remove_team_slugname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_contact',
        ),
        migrations.RemoveField(
            model_name='team',
            name='team_members',
        ),
    ]
