# Generated by Django 3.0.4 on 2020-04-15 06:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aces', '0007_auto_20200415_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_contact',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='team',
            name='team_members',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
