# Generated by Django 3.0.4 on 2020-04-15 07:57

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aces', '0008_auto_20200415_1204'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagecontent', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
