# Generated by Django 3.0.4 on 2020-04-15 17:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aces', '0009_homepagecontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecontent',
            name='event_disp',
            field=models.ManyToManyField(to='aces.Event'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='mentors',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
