# Generated by Django 3.0.4 on 2020-04-16 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aces', '0012_homepagecontent_mentors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepagecontent',
            old_name='mentors',
            new_name='ment_disp',
        ),
    ]
