# Generated by Django 3.0.4 on 2020-04-16 19:20

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aces', '0013_auto_20200416_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_link',
            field=models.URLField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='pagecontent',
            field=ckeditor.fields.RichTextField(max_length=500),
        ),
    ]
