# Generated by Django 3.0.4 on 2020-04-17 06:54

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aces', '0014_auto_20200417_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagecontent',
            name='pagecontent',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.CreateModel(
            name='AboutUsPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vision', ckeditor.fields.RichTextField()),
                ('mission', ckeditor.fields.RichTextField()),
                ('contact', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
