# Generated by Django 3.0.4 on 2020-04-17 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aces', '0015_auto_20200417_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutuspage',
            name='contact',
        ),
    ]
