# Generated by Django 3.0.4 on 2020-04-17 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aces', '0016_remove_aboutuspage_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_link',
            field=models.TextField(),
        ),
    ]
